version: '3.3'

services:
  app:
    build: .
    image: alex2060/hyperwiki-backend
    restart: "no"
    command: ["pip", "install" ,"mysql-connector-python" ]
    command: ["python", "manage.py", "runserver", "0.0.0.0:8000"]
    ports:
      - "8000:8000"
    volumes:
      - ./App:/App
    env_file:
      - .env

  mysql-server:
    image: mysql:8.0.19
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_USERNAME: ${MYSQL_HOST}
      MYSQL_PASSWORD: ${MYSQL_PASS}
      MYSQL_DATABASE: ${}
    volumes:
      - ./data/db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:5.0.1
    restart: always
    environment:
      PMA_HOST: mysql-server
      PMA_USER: root
      PMA_PASSWORD: secret
    ports:
      - "5000:80"
volumes:
  mysql-data:
